{
  "name": "zass-mega-ecosystem-ultimate",
  "version": "20.0.0",
  "description": "THE ULTIMATE ALL-IN-ONE PLATFORM: Browser Engine, Social Media Suite, AI Search, Chat, Downloads, Streaming, E-commerce, Crypto, NFT, Metaverse, AR/VR, IoT, Robotics, Quantum Computing, Bioinformatics, Space Tech - COMPLETE DIGITAL UNIVERSE",
  "license": "UNLICENSED",
  "private": true,
  "author": "ZASS Technologies - Ultimate Edition",
  "homepage": "https://zass-ultimate.com",
  "repository": {
    "type": "git",
    "url": "https://github.com/zass/ultimate-ecosystem"
  },
  "keywords": [
    "browser-engine",
    "social-media-suite",
    "ai-search",
    "ai-chat",
    "download-manager",
    "video-streaming",
    "audio-streaming",
    "ecommerce-platform",
    "crypto-exchange",
    "nft-marketplace",
    "metaverse",
    "ar-vr",
    "iot-platform",
    "robotics-control",
    "quantum-computing",
    "bioinformatics",
    "space-tech",
    "gaming-platform",
    "education-platform",
    "healthcare-system",
    "finance-banking",
    "real-estate",
    "travel-booking",
    "food-delivery",
    "ride-hailing",
    "job-marketplace",
    "freelance-platform",
    "dating-app",
    "fitness-tracker",
    "music-production",
    "video-editing",
    "3d-modeling",
    "cad-software",
    "blockchain",
    "web3",
    "defi",
    "smart-contracts",
    "ai-agents",
    "machine-learning",
    "deep-learning",
    "computer-vision",
    "nlp",
    "speech-recognition",
    "voice-cloning",
    "face-recognition",
    "emotion-detection",
    "gesture-control",
    "brain-computer-interface",
    "robotics",
    "drones",
    "autonomous-vehicles",
    "smart-home",
    "smart-city",
    "supply-chain",
    "logistics",
    "manufacturing",
    "agriculture-tech",
    "climate-tech",
    "renewable-energy",
    "carbon-trading"
  ],
  "main": "dist/ultimate-server.js",
  "types": "dist/types/index.d.ts",
  "scripts": {
    "start": "node dist/ultimate-server.js",
    "dev": "NODE_ENV=development nodemon --exec ts-node src/ultimate-server.ts",
    "dev:all": "npm run dev & npm run dev:microservices & npm run dev:frontend & npm run dev:mobile",
    "dev:microservices": "node scripts/start-all-microservices.js",
    "dev:frontend": "cd frontend && npm run dev",
    "dev:mobile": "cd mobile && npm run start",
    "build": "npm run clean && npm run build:ts && npm run build:copy && npm run build:css && npm run build:js && npm run build:mobile && npm run build:desktop",
    "build:ts": "tsc",
    "build:copy": "copyfiles -u 1 src/**/*.html src/**/*.css src/**/*.json dist/",
    "build:css": "sass src/public/css/ultimate.scss dist/public/css/ultimate.css --style compressed --no-source-map",
    "build:js": "webpack --mode production --config webpack.ultimate.config.js",
    "build:mobile": "cd mobile && npm run build",
    "build:desktop": "cd desktop && npm run build",
    "build:electron": "cd electron && npm run build",
    "build:docker": "docker build -f Dockerfile.ultimate -t zass-ultimate:latest .",
    "clean": "rimraf dist",
    "postinstall": "npm run build && npm run setup:all",
    "setup:all": "node scripts/setup-ultimate.js",
    "setup:database": "node scripts/setup-databases.js",
    "setup:queues": "node scripts/setup-queues.js",
    "setup:cache": "node scripts/setup-cache.js",
    "setup:storage": "node scripts/setup-storage.js",
    "prod": "NODE_ENV=production node cluster-ultimate.js",
    "prod:kubernetes": "kubectl apply -f k8s/ultimate/",
    "prod:aws": "node scripts/deploy-aws-ultimate.js",
    "prod:azure": "node scripts/deploy-azure-ultimate.js",
    "prod:gcp": "node scripts/deploy-gcp-ultimate.js",
    "worker:ai-ml": "node dist/workers/aiMlWorker.js",
    "worker:blockchain": "node dist/workers/blockchainWorker.js",
    "worker:metaverse": "node dist/workers/metaverseWorker.js",
    "worker:iot": "node dist/workers/iotWorker.js",
    "worker:robotics": "node dist/workers/roboticsWorker.js",
    "worker:quantum": "node dist/workers/quantumWorker.js",
    "worker:bioinformatics": "node dist/workers/bioWorker.js",
    "worker:space": "node dist/workers/spaceWorker.js",
    "worker:gaming": "node dist/workers/gamingWorker.js",
    "worker:ar-vr": "node dist/workers/arVrWorker.js",
    "worker:crypto": "node dist/workers/cryptoWorker.js",
    "worker:nft": "node dist/workers/nftWorker.js",
    "worker:defi": "node dist/workers/defiWorker.js",
    "worker:social": "node dist/workers/socialUltimateWorker.js",
    "worker:media": "node dist/workers/mediaUltimateWorker.js",
    "worker:search": "node dist/workers/searchUltimateWorker.js",
    "worker:download": "node dist/workers/downloadUltimateWorker.js",
    "worker:streaming": "node dist/workers/streamingWorker.js",
    "worker:ecommerce": "node dist/workers/ecommerceWorker.js",
    "worker:payment": "node dist/workers/paymentUltimateWorker.js",
    "worker:analytics": "node dist/workers/analyticsWorker.js",
    "worker:ml-training": "node dist/workers/mlTrainingWorker.js",
    "worker:video-processing": "node dist/workers/videoProcessingWorker.js",
    "worker:audio-processing": "node dist/workers/audioProcessingWorker.js",
    "worker:image-processing": "node dist/workers/imageProcessingWorker.js",
    "worker:3d-rendering": "node dist/workers/3dRenderingWorker.js",
    "worker:document-processing": "node dist/workers/documentWorker.js",
    "worker:email-ultimate": "node dist/workers/emailUltimateWorker.js",
    "worker:notification": "node dist/workers/notificationWorker.js",
    "worker:backup-ultimate": "node dist/workers/backupUltimateWorker.js",
    "worker:sync": "node dist/workers/syncWorker.js",
    "worker:migration": "node dist/workers/migrationWorker.js",
    "worker:replication": "node dist/workers/replicationWorker.js",
    "cron:ultimate-all": "node dist/cron/ultimateCron.js",
    "cron:backup-full": "node dist/cron/fullBackup.js",
    "cron:cleanup-ultimate": "node dist/cron/ultimateCleanup.js",
    "cron:analytics-ultimate": "node dist/cron/ultimateAnalytics.js",
    "cron:ml-retrain": "node dist/cron/retrainModels.js",
    "cron:blockchain-sync": "node dist/cron/blockchainSync.js",
    "cron:market-data": "node dist/cron/marketData.js",
    "cron:weather-data": "node dist/cron/weatherData.js",
    "cron:news-aggregation": "node dist/cron/newsAggregator.js",
    "cron:social-trends": "node dist/cron/socialTrends.js",
    "cron:seo-optimization": "node dist/cron/seoOptimizer.js",
    "migrate:ultimate-up": "node dist/database/ultimate-migrate.js up",
    "migrate:ultimate-down": "node dist/database/ultimate-migrate.js down",
    "migrate:shard": "node dist/database/shard-migrate.js",
    "seed:ultimate": "node dist/database/ultimate-seed.js",
    "seed:demo": "node dist/database/demo-seed.js",
    "seed:stress-test": "node dist/database/stress-seed.js",
    "backup:full-ultimate": "node dist/scripts/ultimateFullBackup.js",
    "backup:incremental-ultimate": "node dist/scripts/ultimateIncrementalBackup.js",
    "backup:real-time": "node dist/scripts/realTimeBackup.js",
    "restore:ultimate": "node dist/scripts/ultimateRestore.js",
    "restore:point-in-time": "node dist/scripts/pointInTimeRestore.js",
    "test:ultimate": "NODE_ENV=test jest --coverage --detectOpenHandles --forceExit --maxWorkers=4",
    "test:unit-ultimate": "jest --testPathPattern=unit --coverage",
    "test:integration-ultimate": "jest --testPathPattern=integration --coverage --runInBand",
    "test:e2e-ultimate": "jest --testPathPattern=e2e --runInBand --forceExit",
    "test:performance": "artillery run test/performance/ultimate-load-test.yml",
    "test:stress": "artillery run test/stress/ultimate-stress-test.yml",
    "test:security": "node test/security/security-audit.js",
    "test:penetration": "node test/security/penetration-test.js",
    "test:blockchain": "truffle test test/blockchain/",
    "test:smart-contracts": "hardhat test test/smart-contracts/",
    "lint:ultimate": "eslint src --ext .ts,.tsx,.js,.jsx --fix --max-warnings 0",
    "lint:strict": "eslint src --ext .ts,.tsx,.js,.jsx --fix --rule 'no-console: error' --rule 'no-debugger: error'",
    "format:ultimate": "prettier --write 'src/**/*.{ts,tsx,js,jsx,json,md,yml,yaml,css,scss}'",
    "format:check": "prettier --check 'src/**/*.{ts,tsx,js,jsx,json,md,yml,yaml,css,scss}'",
    "type-check:ultimate": "tsc --noEmit --strict",
    "analyze:bundle": "webpack-bundle-analyzer dist/stats.json",
    "analyze:performance": "node scripts/performance-analyzer.js",
    "analyze:coverage": "nyc report --reporter=html --reporter=lcov",
    "audit:ultimate": "npm audit && snyk test && npm audit fix --force",
    "audit:security": "node scripts/security-audit.js && npm audit --json > audit-report.json",
    "audit:dependencies": "npm-check --skip-unused --update",
    "security:ultimate": "npm run audit:ultimate && node scripts/ultimate-security-check.js && npm run test:security",
    "security:scan": "node scripts/vulnerability-scan.js",
    "security:firewall": "node scripts/configure-firewall.js",
    "security:ddos-protection": "node scripts/ddos-protection.js",
    "docs:ultimate": "typedoc --out docs/api src/ && npm run docs:swagger && npm run docs:storybook",
    "docs:swagger": "swagger-cli validate swagger-ultimate.yaml && redoc-cli bundle swagger-ultimate.yaml -o docs/redoc-static.html",
    "docs:storybook": "cd frontend && npm run build-storybook",
    "docs:wiki": "node scripts/generate-wiki.js",
    "benchmark:ultimate": "node scripts/ultimate-benchmark.js",
    "benchmark:database": "node scripts/database-benchmark.js",
    "benchmark:cache": "node scripts/cache-benchmark.js",
    "benchmark:queue": "node scripts/queue-benchmark.js",
    "profile:ultimate": "node --prof dist/ultimate-server.js && node --prof-process isolate-*.log > profile-ultimate.txt",
    "profile:memory": "node --inspect --max-old-space-size=8192 dist/ultimate-server.js",
    "profile:heap": "node --heap-prof dist/ultimate-server.js",
    "monitor:ultimate": "node scripts/ultimate-monitor.js",
    "monitor:real-time": "pm2 monit && node scripts/realtime-monitor.js",
    "monitor:grafana": "docker-compose -f docker-compose.grafana.yml up -d",
    "monitor:prometheus": "node scripts/prometheus-exporter.js",
    "logs:ultimate": "tail -f logs/ultimate-combined.log",
    "logs:error-ultimate": "tail -f logs/ultimate-error.log",
    "logs:audit": "tail -f logs/audit.log",
    "logs:access": "tail -f logs/access.log",
    "logs:performance": "tail -f logs/performance.log",
    "logs:security": "tail -f logs/security.log",
    "health:ultimate": "curl http://localhost:3000/health/ultimate | jq",
    "health:all-services": "node scripts/health-check-all.js",
    "health:database": "node scripts/database-health.js",
    "health:redis": "node scripts/redis-health.js",
    "health:queue": "node scripts/queue-health.js",
    "metrics:ultimate": "curl http://localhost:3000/metrics/ultimate | jq",
    "metrics:business": "curl http://localhost:3000/metrics/business | jq",
    "metrics:technical": "curl http://localhost:3000/metrics/technical | jq",
    "db:connect-ultimate": "node scripts/ultimate-db-connect.js",
    "db:repair-ultimate": "node scripts/ultimate-db-repair.js",
    "db:optimize-ultimate": "node scripts/ultimate-db-optimize.js",
    "db:shard": "node scripts/database-sharding.js",
    "db:replicate": "node scripts/database-replication.js",
    "db:backup-live": "node scripts/live-database-backup.js",
    "cache:clear-ultimate": "node scripts/ultimate-clear-cache.js",
    "cache:warm": "node scripts/warm-cache.js",
    "cache:optimize": "node scripts/optimize-cache.js",
    "queue:clean-ultimate": "node scripts/ultimate-clean-queues.js",
    "queue:monitor": "node scripts/queue-monitor.js",
    "queue:retry-failed": "node scripts/retry-failed-jobs.js",
    "update:ultimate": "npm update && npm audit fix --force && npm run security:audit && npm run test:ultimate",
    "update:deps-ultimate": "npx npm-check-updates -u && npm install && npm run build",
    "update:migrations": "node scripts/run-all-migrations.js",
    "docker:build-ultimate": "docker build -f Dockerfile.ultimate -t zass-ultimate:latest .",
    "docker:build-prod": "docker build -f Dockerfile.prod-ultimate -t zass-ultimate:prod .",
    "docker:up-ultimate": "docker-compose -f docker-compose.ultimate.yml up -d",
    "docker:up-dev": "docker-compose -f docker-compose.dev-ultimate.yml up -d",
    "docker:down-ultimate": "docker-compose -f docker-compose.ultimate.yml down",
    "docker:down-volumes": "docker-compose -f docker-compose.ultimate.yml down -v",
    "docker:logs-ultimate": "docker-compose -f docker-compose.ultimate.yml logs -f",
    "docker:prune-ultimate": "docker system prune -a -f && docker volume prune -f",
    "docker:ps": "docker-compose -f docker-compose.ultimate.yml ps",
    "docker:exec": "docker exec -it zass-ultimate bash",
    "kubernetes:apply-ultimate": "kubectl apply -f k8s/ultimate/",
    "kubernetes:delete-ultimate": "kubectl delete -f k8s/ultimate/",
    "kubernetes:rollout-ultimate": "kubectl rollout restart deployment/zass-ultimate",
    "kubernetes:scale": "kubectl scale deployment/zass-ultimate --replicas=10",
    "kubernetes:logs": "kubectl logs -f deployment/zass-ultimate",
    "kubernetes:port-forward": "kubectl port-forward service/zass-ultimate 3000:3000",
    "pm2:start-ultimate": "pm2 start ecosystem.ultimate.config.js",
    "pm2:stop-ultimate": "pm2 stop ecosystem.ultimate.config.js",
    "pm2:restart-ultimate": "pm2 restart ecosystem.ultimate.config.js",
    "pm2:reload-ultimate": "pm2 reload ecosystem.ultimate.config.js",
    "pm2:delete-ultimate": "pm2 delete ecosystem.ultimate.config.js",
    "pm2:logs-ultimate": "pm2 logs zass-ultimate",
    "pm2:monit-ultimate": "pm2 monit",
    "pm2:status-ultimate": "pm2 status",
    "nginx:reload-ultimate": "sudo nginx -s reload",
    "nginx:config-test": "sudo nginx -t",
    "nginx:restart": "sudo systemctl restart nginx",
    "deploy:staging-ultimate": "node scripts/deploy-ultimate-staging.js",
    "deploy:production-ultimate": "node scripts/deploy-ultimate-production.js",
    "deploy:canary": "node scripts/canary-deploy.js",
    "deploy:blue-green": "node scripts/blue-green-deploy.js",
    "rollback:ultimate": "node scripts/ultimate-rollback.js",
    "rollback:database": "node scripts/database-rollback.js",
    "maintenance:on-ultimate": "node scripts/ultimate-maintenance-on.js",
    "maintenance:off-ultimate": "node scripts/ultimate-maintenance-off.js",
    "maintenance:status": "node scripts/maintenance-status.js",
    "ssl:renew-ultimate": "certbot renew --nginx && node scripts/update-ssl-certs.js",
    "ssl:generate": "node scripts/generate-ssl-certs.js",
    "backup:schedule": "node scripts/schedule-backups.js",
    "recovery:disaster": "node scripts/disaster-recovery.js",
    "recovery:data-corruption": "node scripts/data-corruption-recovery.js",
    "analytics:dashboard": "node scripts/start-analytics-dashboard.js",
    "analytics:reports": "node scripts/generate-reports.js",
    "analytics:export": "node scripts/export-analytics.js",
    "ai:train-models": "node scripts/train-ai-models.js",
    "ai:evaluate-models": "node scripts/evaluate-models.js",
    "ai:deploy-models": "node scripts/deploy-models.js",
    "blockchain:deploy-contracts": "truffle migrate --network mainnet",
    "blockchain:verify-contracts": "hardhat verify",
    "blockchain:interact": "node scripts/blockchain-interact.js",
    "crypto:start-exchange": "node scripts/start-crypto-exchange.js",
    "crypto:update-rates": "node scripts/update-crypto-rates.js",
    "nft:mint": "node scripts/mint-nft.js",
    "nft:marketplace-start": "node scripts/start-nft-marketplace.js",
    "metaverse:start-world": "node scripts/start-metaverse.js",
    "metaverse:create-assets": "node scripts/create-metaverse-assets.js",
    "iot:start-gateway": "node scripts/start-iot-gateway.js",
    "iot:monitor-devices": "node scripts/monitor-iot-devices.js",
    "robotics:control-center": "node scripts/start-robotics-control.js",
    "robotics:simulate": "node scripts/robotics-simulation.js",
    "quantum:simulate": "node scripts/quantum-simulation.js",
    "quantum:optimize": "node scripts/quantum-optimization.js",
    "bio:analyze-genome": "node scripts/analyze-genome.js",
    "bio:protein-folding": "node scripts/protein-folding.js",
    "space:track-satellites": "node scripts/track-satellites.js",
    "space:orbit-calculations": "node scripts/orbit-calculations.js"
  },
  "dependencies": {
    "@3d/rendering-engine": "^5.0.0",
    "@adobe/creative-cloud-sdk": "^4.0.0",
    "@ai/chat-models": "^3.0.0",
    "@analytics/real-time": "^2.0.0",
    "@ar/vr-framework": "^8.0.0",
    "@aws-sdk/client-bedrock": "^3.485.0",
    "@aws-sdk/client-sagemaker": "^3.485.0",
    "@azure/cognitiveservices-computervision": "^8.0.0",
    "@azure/identity": "^4.0.0",
    "@blockchain/ethereum-sdk": "^7.0.0",
    "@blockchain/solana-sdk": "^2.0.0",
    "@braintree/sanitize-url": "^7.0.0",
    "@capacitor/android": "^5.0.0",
    "@capacitor/core": "^5.0.0",
    "@capacitor/ios": "^5.0.0",
    "@cloudflare/workers-types": "^4.0.0",
    "@coinbase/coinbase-sdk": "^4.0.0",
    "@compass/ai-recommendations": "^3.0.0",
    "@crypto/exchange-sdk": "^6.0.0",
    "@deeplearning/tensorflow-models": "^4.0.0",
    "@defi/protocol-sdk": "^3.0.0",
    "@discord/embedded-app-sdk": "^1.0.0",
    "@elastic/apm-rum": "^5.0.0",
    "@electron/remote": "^2.0.0",
    "@firebase/app": "^0.10.0",
    "@firebase/messaging": "^0.12.0",
    "@gaming/engine-unreal": "^5.0.0",
    "@google-cloud/aiplatform": "^3.0.0",
    "@google-cloud/dialogflow": "^6.0.0",
    "@google-cloud/vision": "^4.0.0",
    "@grpc/grpc-js": "^1.10.0",
    "@huggingface/inference": "^2.0.0",
    "@iot/device-sdk": "^5.0.0",
    "@langchain/anthropic": "^0.1.0",
    "@langchain/cohere": "^0.1.0",
    "@langchain/google-genai": "^0.0.10",
    "@langchain/mistralai": "^0.0.10",
    "@metaverse/avatar-sdk": "^4.0.0",
    "@metaverse/world-engine": "^3.0.0",
    "@microsoft/teams-js": "^2.0.0",
    "@motion-canvas/core": "^3.0.0",
    "@nestjs/event-emitter": "^2.0.0",
    "@nestjs/throttler": "^5.0.0",
    "@ngrx/store": "^17.0.0",
    "@nft/marketplace-sdk": "^5.0.0",
    "@nomicfoundation/hardhat-toolbox": "^4.0.0",
    "@opensea/seaport-js": "^4.0.0",
    "@paypal/payouts-sdk": "^2.0.0",
    "@pinecone-database/pinecone": "^1.0.0",
    "@pixi/js": "^7.0.0",
    "@playwright/test": "^1.40.0",
    "@pulumi/aws": "^6.0.0",
    "@pulumi/pulumi": "^3.0.0",
    "@puppeteer/browsers": "^1.9.0",
    "@qdrant/js-client-rest": "^1.8.0",
    "@quantum/qiskit-sdk": "^0.45.0",
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-navigation/native": "^6.1.0",
    "@reduxjs/toolkit": "^2.0.0",
    "@renovate/renovate": "^37.0.0",
    "@replicate/replicate": "^0.25.0",
    "@robotics/roslib": "^3.0.0",
    "@sentry/nextjs": "^7.88.0",
    "@shopify/hydrogen": "^2024.1.0",
    "@slack/bolt": "^3.0.0",
    "@spacex/api-sdk": "^2.0.0",
    "@stellar/stellar-sdk": "^11.0.0",
    "@stripe/connect-js": "^3.0.0",
    "@supabase/supabase-js": "^2.39.0",
    "@tensorflow-models/face-detection": "^0.0.1",
    "@tensorflow-models/hand-pose-detection": "^0.0.1",
    "@tensorflow-models/speech-commands": "^0.0.1",
    "@testing-library/react": "^14.1.0",
    "@threejs/ar": "^2.0.0",
    "@tradingview/charting-library": "^25.0.0",
    "@trpc/server": "^10.45.0",
    "@truffle/contract": "^4.6.0",
    "@types/three": "^0.160.0",
    "@unreal-engine/blueprint-sdk": "^5.0.0",
    "@vue/composition-api": "^1.7.0",
    "@web3/auth-sdk": "^3.0.0",
    "@webassemblyjs/wasm-parser": "^1.11.0",
    "@xr/ar-foundation": "^4.0.0",
    "abseil": "^0.3.0",
    "acorn": "^8.11.0",
    "aes256": "^1.1.0",
    "affine-cipher": "^1.0.0",
    "agentkeepalive": "^4.5.0",
    "agora-rtc-sdk-ng": "^4.0.0",
    "alchemy-sdk": "^3.0.0",
    "amazon-cognito-identity-js": "^6.3.0",
    "amqp-connection-manager": "^4.1.0",
    "analytics-node": "^6.0.0",
    "angular": "^17.0.0",
    "antd": "^5.12.0",
    "apexcharts": "^3.45.0",
    "apollo-client": "^3.8.0",
    "app-root-path": "^3.1.0",
    "arduino-connector": "^2.0.0",
    "asana": "^2.0.0",
    "async-retry": "^1.3.3",
    "at-least-node": "^1.0.0",
    "atlassian-jwt": "^2.0.0",
    "awesomplete": "^1.1.0",
    "axios-cache-interceptor": "^1.3.0",
    "axios-rate-limit": "^1.3.0",
    "babel-core": "^7.0.0-bridge.0",
    "backblaze-b2": "^2.0.0",
    "balance-loader": "^1.0.0",
    "bcrypt": "^5.1.0",
    "bignumber.js": "^9.1.0",
    "binance-api-node": "^4.0.0",
    "bitcoinjs-lib": "^6.1.0",
    "blakejs": "^1.2.0",
    "blend2d": "^2.0.0",
    "blessed": "^0.1.81",
    "blob-polyfill": "^9.0.0",
    "blockly": "^10.0.0",
    "blueimp-md5": "^2.19.0",
    "body-parser": "^1.20.0",
    "bootstrap": "^5.3.0",
    "braintree": "^3.0.0",
    "bree": "^9.0.0",
    "browserify": "^17.0.0",
    "bs58": "^5.0.0",
    "bullmq": "^5.0.0",
    "busboy": "^1.6.0",
    "cacache": "^18.0.0",
    "cacheable-lookup": "^6.0.0",
    "cached-path-relative": "^1.1.0",
    "caniuse-lite": "^1.0.30001570",
    "canvas": "^2.11.0",
    "casper-js-sdk": "^1.0.0",
    "celery-node": "^5.0.0",
    "chalk": "^5.3.0",
    "chokidar": "^3.5.0",
    "chroma-js": "^2.4.0",
    "cipher-base": "^1.0.4",
    "circleci-api": "^4.0.0",
    "ckeditor5": "^40.0.0",
    "clarifai-nodejs": "^9.0.0",
    "class-validator-jsonschema": "^5.0.0",
    "clevertap-web-sdk": "^2.0.0",
    "cloudinary": "^2.0.0",
    "cluster": "^0.7.7",
    "cmake-js": "^7.0.0",
    "cohere-ai": "^7.0.0",
    "coinbase-commerce-node": "^3.0.0",
    "coinpayments": "^1.0.0",
    "colorthief": "^2.3.0",
    "commander": "^11.0.0",
    "commitizen": "^4.3.0",
    "common-tags": "^1.8.0",
    "concurrently": "^8.2.0",
    "connect-pg-simple": "^9.0.0",
    "consul": "^1.1.0",
    "contentful": "^10.0.0",
    "convict": "^6.2.0",
    "cookie-session": "^2.0.0",
    "cookies": "^0.8.0",
    "copy-to-clipboard": "^3.3.0",
    "core-js": "^3.34.0",
    "cors-anywhere": "^0.4.0",
    "couchbase": "^4.0.0",
    "croner": "^8.0.0",
    "cross-fetch": "^4.0.0",
    "crypto-browserify": "^3.12.0",
    "crypto-js": "^4.2.0",
    "cryptocurrency-icons": "^0.18.0",
    "dagre": "^0.8.5",
    "daisyui": "^4.4.0",
    "dataloader": "^2.2.0",
    "datadog-metrics": "^0.10.0",
    "dateformat": "^5.0.0",
    "dayjs": "^1.11.0",
    "db-migrate": "^1.0.0",
    "deep-diff": "^1.0.2",
    "deep-freeze": "^0.0.1",
    "deepdash": "^5.3.0",
    "delayed-stream": "^1.0.0",
    "detect-port": "^1.5.0",
    "devtools-protocol": "^0.0.1244750",
    "diff-match-patch": "^1.0.5",
    "discord-api-types": "^0.37.0",
    "dockerode": "^4.0.0",
    "docusaurus": "^3.0.0",
    "dom-to-image": "^2.6.0",
    "domino": "^2.1.6",
    "dot-prop": "^9.0.0",
    "dtrace-provider": "^0.8.8",
    "easy-peasy": "^6.0.0",
    "eccrypto": "^1.1.0",
    "ecdsa-secp256k1": "^1.0.0",
    "eciesjs": "^0.3.0",
    "editorjs": "^2.0.0",
    "electron": "^27.0.0",
    "electron-builder": "^24.6.0",
    "electron-updater": "^6.1.0",
    "elliptic": "^6.5.4",
    "emoji-regex": "^10.3.0",
    "emojilib": "^3.0.0",
    "envalid": "^8.0.0",
    "errorhandler": "^1.5.1",
    "esbuild": "^0.19.0",
    "eslint-config-next": "^14.0.0",
    "etag": "^1.8.1",
    "ethereumjs-util": "^7.1.0",
    "ethereumjs-wallet": "^1.0.0",
    "ethersproject": "^5.7.0",
    "event-emitter": "^0.3.5",
    "event-source-polyfill": "^1.0.0",
    "eventemitter2": "^6.4.0",
    "eventemitter3": "^5.0.0",
    "evergreen-ui": "^7.0.0",
    "excel4node": "^1.8.0",
    "express-async-errors": "^3.1.0",
    "express-cluster": "^0.0.9",
    "express-fileupload": "^1.4.0",
    "express-flash": "^0.0.2",
    "express-formidable": "^1.2.0",
    "express-handlebars": "^7.0.0",
    "express-pino-logger": "^7.0.0",
    "express-static-gzip": "^2.1.0",
    "extract-zip": "^2.0.0",
    "fabric": "^5.3.0",
    "facebook-chat-api": "^1.10.0",
    "fast-csv": "^5.0.0",
    "fast-glob": "^3.3.0",
    "fast-json-patch": "^3.1.0",
    "fast-levenshtein": "^3.0.0",
    "fast-memoize": "^2.5.2",
    "fast-redact": "^3.3.0",
    "fast-safe-stringify": "^2.1.1",
    "fast-xml-parser": "^4.3.0",
    "fastify": "^4.24.0",
    "faye-websocket": "^0.11.4",
    "fb": "^2.0.0",
    "feathersjs": "^5.0.0",
    "fhir-kit-client": "^2.0.0",
    "figlet": "^1.6.0",
    "file-system-cache": "^2.0.0",
    "file-type": "^18.0.0",
    "filesize": "^10.0.0",
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^4.4.0",
    "flat": "^6.0.0",
    "flatted": "^3.2.0",
    "flux": "^4.0.0",
    "fmix": "^0.1.0",
    "follow-redirects": "^1.15.0",
    "forever": "^4.0.0",
    "forge": "^1.3.0",
    "formidable": "^3.5.0",
    "fortnite-api": "^4.0.0",
    "fp-ts": "^2.16.0",
    "fresh": "^0.5.2",
    "fs-capacitor": "^8.0.0",
    "fs-extra-promise": "^1.0.0",
    "fuse.js": "^7.0.0",
    "gaxios": "^6.0.0",
    "gcp-metadata": "^6.0.0",
    "generic-pool": "^3.9.0",
    "geoip-lite": "^1.4.0",
    "geolib": "^3.3.0",
    "get-port": "^7.0.0",
    "get-stream": "^8.0.0",
    "gh-pages": "^6.0.0",
    "git-repo-info": "^2.1.0",
    "git-rev-sync": "^3.0.0",
    "github-api": "^3.4.0",
    "glob": "^10.3.0",
    "global-agent": "^3.0.0",
    "global-dirs": "^4.0.0",
    "google-map-react": "^2.2.0",
    "google-protobuf": "^3.21.0",
    "google-spreadsheet": "^4.0.0",
    "got": "^13.0.0",
    "graceful-fs": "^4.2.0",
    "graphile-worker": "^0.14.0",
    "graphql-query-complexity": "^0.12.0",
    "graphql-rate-limit": "^3.3.0",
    "graphql-subscriptions": "^2.0.0",
    "graphql-tag": "^2.12.0",
    "graphql-type-json": "^0.3.2",
    "grid-layout": "^1.0.0",
    "grpc-promisify": "^1.0.0",
    "gsap": "^3.12.0",
    "gtoken": "^7.0.0",
    "gulp-uglify": "^3.0.0",
    "gzip-size": "^7.0.0",
    "h3": "^1.9.0",
    "handlebars-helpers": "^0.10.0",
    "hapi": "^18.1.0",
    "happn": "^3.0.0",
    "hardhat": "^2.19.0",
    "hash.js": "^1.1.7",
    "hashids": "^2.3.0",
    "hashring": "^3.2.0",
    "helmet-csp": "^4.0.0",
    "hex-rgb": "^5.0.0",
    "highlight.js": "^11.9.0",
    "history": "^5.3.0",
    "hls.js": "^1.4.0",
    "html-minifier-terser": "^7.2.0",
    "html-webpack-plugin": "^5.5.0",
    "html2canvas": "^1.4.1",
    "http-errors": "^2.0.0",
    "http-proxy": "^1.18.1",
    "http2": "^3.3.7",
    "http2-wrapper": "^2.2.0",
    "https-proxy-agent": "^7.0.0",
    "hubspot-api": "^2.0.0",
    "humanize-duration": "^3.31.0",
    "humanize-string": "^3.0.0",
    "hyperlinker": "^1.0.0",
    "i18next": "^23.7.0",
    "i18next-http-backend": "^2.3.0",
    "iconv-lite": "^0.6.3",
    "idb": "^8.0.0",
    "image-downloader": "^4.3.0",
    "image-size": "^1.0.0",
    "immer": "^10.0.0",
    "immutable": "^4.3.0",
    "imurmurhash": "^0.1.4",
    "inflection": "^2.0.1",
    "inherits": "^2.0.4",
    "ini": "^4.1.0",
    "ink": "^4.0.0",
    "inquirer": "^9.2.0",
    "insight": "^0.11.0",
    "instapromise": "^1.0.0",
    "integral": "^1.0.0",
    "intercept-stdout": "^0.1.2",
    "interpret": "^3.1.0",
    "intl": "^1.2.5",
    "inversify": "^6.0.0",
    "ip": "^2.0.0",
    "ip-cidr": "^3.0.0",
    "ipaddr.js": "^2.1.0",
    "ipfs-http-client": "^60.0.0",
    "is-ci": "^3.0.0",
    "is-docker": "^3.0.0",
    "is-online": "^11.0.0",
    "is-reachable": "^7.0.0",
    "is-stream": "^3.0.0",
    "is-wsl": "^3.0.0",
    "isomorphic-fetch": "^3.0.0",
    "isomorphic-git": "^1.24.0",
    "isomorphic-ws": "^5.0.0",
    "jake": "^10.8.0",
    "javascript-obfuscator": "^4.1.0",
    "jayson": "^4.0.0",
    "jest-environment-jsdom": "^29.7.0",
    "joi-password-complexity": "^6.0.0",
    "jose": "^5.0.0",
    "jotai": "^2.5.0",
    "jpegtran-bin": "^7.0.0",
    "jquery": "^3.7.0",
    "js-beautify": "^1.14.0",
    "js-cookie": "^3.0.0",
    "js-graph-algorithms": "^1.0.0",
    "js-md5": "^0.8.0",
    "js-sha256": "^0.10.0",
    "js-sha3": "^0.9.0",
    "js-tiktoken": "^1.0.0",
    "js-yaml": "^4.1.0",
    "jscodeshift": "^0.15.0",
    "jsdom-global": "^3.0.2",
    "jsesc": "^3.0.0",
    "json-bigint": "^1.0.0",
    "json-diff": "^1.0.0",
    "json-logic-js": "^2.0.0",
    "json-query": "^2.2.2",
    "json-rpc-2.0": "^1.6.0",
    "json-schema": "^0.4.0",
    "json-schema-ref-parser": "^11.0.0",
    "json-schema-traverse": "^1.0.0",
    "json-stable-stringify": "^1.0.2",
    "json-stringify-safe": "^5.0.1",
    "json-to-pretty-yaml": "^1.2.2",
    "json-type-validation": "^1.0.0",
    "json5": "^2.2.0",
    "jsonapi-serializer": "^3.6.0",
    "jsonata": "^2.0.0",
    "jsonld": "^8.3.0",
    "jsonpack": "^1.1.5",
    "jsonpath": "^1.1.1",
    "jsonwebtoken-promisify": "^1.0.0",
    "jsonschema": "^1.4.0",
    "jsontoxml": "^1.0.1",
    "jsqr": "^1.4.0",
    "jsx-to-string": "^1.4.0",
    "juice": "^9.0.0",
    "jwa": "^2.0.0",
    "jwk-to-pem": "^2.0.0",
    "jwks-rsa": "^3.0.0",
    "jws": "^4.0.0",
    "k6": "^0.0.0",
    "kafkajs-snappy": "^1.0.0",
    "karma": "^6.4.0",
    "keycloak-connect": "^22.0.0",
    "keygrip": "^1.1.0",
    "keyv": "^4.5.0",
    "klaw": "^4.1.0",
    "knex": "^3.0.0",
    "koa": "^2.14.0",
    "kubernetes-client": "^9.0.0",
    "langdetect": "^0.2.1",
    "language-subtag-registry": "^0.3.0",
    "layercake": "^8.0.0",
    "layout-base": "^2.0.0",
    "ldapjs": "^3.0.0",
    "leaky-bucket": "^2.0.0",
    "leven": "^4.0.0",
    "libphonenumber-js": "^1.10.0",
    "libsodium-wrappers": "^0.7.0",
    "light-my-request": "^5.0.0",
    "lightningcss": "^1.22.0",
    "limiter": "^2.1.0",
    "linkifyjs": "^4.1.0",
    "listr": "^0.14.3",
    "lit": "^3.0.0",
    "localforage": "^1.10.0",
    "lockfile": "^1.0.4",
    "lodash-deep": "^2.0.0",
    "lodash-id": "^0.14.1",
    "lodash-webpack-plugin": "^0.11.6",
    "log-update": "^6.0.0",
    "long": "^5.2.0",
    "loose-envify": "^1.4.0",
    "lorem-ipsum": "^2.0.0",
    "lru-cache": "^10.1.0",
    "lz-string": "^1.5.0",
    "mailchimp-api-v3": "^1.0.0",
    "mailgun-js": "^0.22.0",
    "make-dir": "^4.0.0",
    "mapbox-gl": "^3.0.0",
    "markdown-pdf": "^11.0.0",
    "markdown-to-jsx": "^7.3.0",
    "masonry-layout": "^4.2.0",
    "match-sorter": "^6.3.0",
    "mathjs": "^12.0.0",
    "md5": "^2.3.0",
    "md5-file": "^5.0.0",
    "mdns": "^2.7.0",
    "media-typer": "^1.1.0",
    "memcached": "^2.2.2",
    "memoizee": "^0.4.15",
    "merge-descriptors": "^1.0.1",
    "merge-stream": "^2.0.0",
    "method-override": "^3.0.0",
    "metrics": "^0.1.21",
    "micro": "^10.0.0",
    "micro-cors": "^0.1.1",
    "micro-ft": "^0.3.0",
    "micromatch": "^4.0.5",
    "microrouter": "^3.1.3",
    "migrate": "^2.0.0",
    "mime": "^3.0.0",
    "mime-db": "^1.52.0",
    "mime-types": "^2.1.35",
    "mimic-fn": "^4.0.0",
    "mimic-response": "^4.0.0",
    "min-indent": "^1.0.1",
    "mini-css-extract-plugin": "^2.7.0",
    "minimalistic-assert": "^1.0.1",
    "minimalistic-crypto-utils": "^1.0.1",
    "minimatch": "^9.0.0",
    "minimist": "^1.2.8",
    "minio": "^7.1.0",
    "mixpanel": "^2.0.0",
    "mkdirp": "^3.0.0",
    "ml-classify-text": "^2.0.0",
    "ml-levenberg-marquardt": "^3.0.0",
    "ml-regression": "^2.0.0",
    "mobx": "^6.10.0",
    "mobx-react": "^9.0.0",
    "modclean": "^3.0.0",
    "modern-normalize": "^2.0.0",
    "module-alias": "^2.2.0",
    "moment": "^2.29.0",
    "moment-timezone": "^0.5.0",
    "mongodb-client-encryption": "^6.0.0",
    "mongodb-memory-server-core": "^9.0.0",
    "mongoose-autopopulate": "^1.0.0",
    "mongoose-encryption": "^2.1.0",
    "mongoose-lean-virtuals": "^0.9.0",
    "mongoose-sequence": "^6.0.0",
    "mongoose-slug-generator": "^2.0.0",
    "mongoose-unique-validator": "^4.0.0",
    "morgan-json": "^4.0.0",
    "motion": "^10.0.0",
    "mp3-duration": "^1.1.0",
    "mqtt": "^5.0.0",
    "ms": "^2.1.3",
    "multer-gridfs-storage": "^5.0.0",
    "multiformats": "^13.0.0",
    "multiparty": "^4.2.0",
    "mustache": "^4.2.0",
    "mysql2": "^3.6.0",
    "mz": "^2.7.0",
    "n8n-core": "^0.200.0",
    "n8n-workflow": "^0.200.0",
    "nan": "^2.18.0",
    "nano": "^10.1.0",
    "nanoid": "^5.0.4",
    "native-dns": "^0.7.0",
    "natural-compare": "^1.4.0",
    "nconf": "^0.12.0",
    "nedb": "^1.8.0",
    "needle": "^3.2.0",
    "negotiator": "^0.6.3",
    "neo-async": "^2.6.2",
    "nest-raven": "^10.0.0",
    "net": "^1.0.2",
    "next": "^14.0.0",
    "next-auth": "^5.0.0",
    "next-i18next": "^15.0.0",
    "next-redux-wrapper": "^8.0.0",
    "ngrok": "^5.0.0",
    "nice-napi": "^1.0.0",
    "nifty-connect": "^2.0.0",
    "nightmare": "^3.0.0",
    "nock": "^13.4.0",
    "node-2fa": "^2.0.0",
    "node-abort-controller": "^3.0.0",
    "node-addon-api": "^7.0.0",
    "node-cache-manager": "^2.0.0",
    "node-cleanup": "^2.1.2",
    "node-clock": "^2.0.0",
    "node-cron-2": "^1.0.0",
    "node-dir": "^0.1.17",
    "node-emoji": "^2.0.0",
    "node-fetch-native": "^1.6.0",
    "node-forge": "^1.3.0",
    "node-gyp": "^10.0.0",
    "node-html-to-image": "^4.0.0",
    "node-int64": "^0.4.0",
    "node-ipc": "^9.2.0",
    "node-jose": "^2.2.0",
    "node-localstorage": "^3.0.0",
    "node-mailjet": "^6.0.0",
    "node-mocks-http": "^1.13.0",
    "node-notifier": "^10.0.0",
    "node-oauth1": "^1.2.0",
    "node-opcua": "^2.100.0",
    "node-os-utils": "^1.3.0",
    "node-persist": "^4.0.0",
    "node-pg": "^0.4.0",
    "node-polyfill-webpack-plugin": "^3.0.0",
    "node-pre-gyp": "^0.17.0",
    "node-quickbooks": "^2.4.0",
    "node-rdkafka": "^2.17.0",
    "node-red": "^3.1.0",
    "node-redis": "^4.0.0",
    "node-resque": "^9.0.0",
    "node-sass-middleware": "^1.0.0",
    "node-semver": "^1.0.0",
    "node-snap7": "^0.5.0",
    "node-sql-parser": "^5.0.0",
    "node-ssh": "^13.0.0",
    "node-static": "^0.7.11",
    "node-statsd": "^0.1.1",
    "node-stream-zip": "^1.15.0",
    "node-telegram-bot-api": "^0.61.0",
    "node-tensorflow": "^1.0.0",
    "node-vault": "^0.10.0",
    "node-watchdog": "^0.2.0",
    "node-webcam": "^0.8.0",
    "node-window-manager": "^2.2.0",
    "node-xmpp-client": "^3.2.0",
    "node-zendesk": "^2.0.0",
    "node-zookeeper-client": "^1.1.0",
    "nodemailer-smtp-transport": "^2.7.4",
    "nopt": "^7.2.0",
    "normalize-url": "^8.0.0",
    "notp": "^2.0.3",
    "npm": "^10.2.0",
    "npm-check-updates": "^16.14.0",
    "npm-package-json-lint": "^7.0.0",
    "npm-run-all": "^4.1.5",
    "nssocket": "^0.6.0",
    "ntp-client": "^0.5.3",
    "numeral": "^2.0.6",
    "object-hash": "^3.0.0",
    "object-path": "^0.11.8",
    "objection": "^3.1.0",
    "oboe": "^2.1.5",
    "octokit": "^3.1.0",
    "officegen": "^0.6.0",
    "ogg": "^1.0.0",
    "on-finished": "^2.4.1",
    "on-headers": "^1.0.2",
    "once": "^1.4.0",
    "onetime": "^6.0.0",
    "ono": "^7.1.0",
    "open": "^9.0.0",
    "openai-edge": "^1.0.0",
    "opentelemetry": "^0.24.0",
    "optimist": "^0.6.1",
    "optional": "^0.1.4",
    "options": "^0.0.6",
    "ora": "^7.0.0",
    "os": "^0.1.2",
    "os-locale": "^6.0.0",
    "os-utils": "^0.0.14",
    "otplib": "^12.0.0",
    "owasp-password-strength-test": "^1.3.0",
    "p-cancelable": "^4.0.0",
    "p-defer": "^4.0.0",
    "p-event": "^6.0.0",
    "p-finally": "^2.0.0",
    "p-limit": "^5.0.0",
    "p-locate": "^6.0.0",
    "p-map": "^6.0.0",
    "p-queue": "^7.4.0",
    "p-retry": "^6.0.0",
    "p-series": "^3.0.0",
    "p-timeout": "^6.0.0",
    "p-wait-for": "^5.0.0",
    "package-json": "^8.1.0",
    "pad": "^3.2.0",
    "pako": "^2.1.0",
    "parallel-transform": "^1.2.0",
    "parent-require": "^1.0.0",
    "parse-data-url": "^5.0.0",
    "parse-domain": "^7.0.0",
    "parse-git-config": "^3.0.0",
    "parse-headers": "^2.0.5",
    "parse-json": "^7.0.0",
    "parse-link-header": "^2.0.0",
    "parse-ms": "^3.0.0",
    "parse-numeric-range": "^1.3.0",
    "parse-path": "^7.0.0",
    "parse-url": "^8.1.0",
    "parse5": "^7.1.0",
    "parse5-htmlparser2-tree-adapter": "^7.0.0",
    "parser-toolkit": "^1.0.0",
    "pascalcase": "^2.0.0",
    "passport-anonymous": "^1.0.0",
    "passport-apple": "^2.0.0",
    "passport-auth0": "^1.4.0",
    "passport-azure-ad": "^4.3.0",
    "passport-bitbucket-oauth2": "^1.0.0",
    "passport-digitalocean": "^0.2.0",
    "passport-discord": "^1.0.0",
    "passport-dropbox-oauth2": "^1.0.0",
    "passport-github2": "^0.1.12",
    "passport-gitlab2": "^5.0.0",
    "passport-google-oauth": "^2.0.0",
    "passport-http": "^0.3.0",
    "passport-http-bearer": "^1.0.1",
    "passport-linkedin-oauth2": "^2.0.0",
    "passport-local-mongoose": "^8.0.0",
    "passport-oauth2-client-password": "^0.1.2",
    "passport-oauth2-refresh": "^2.1.0",
    "passport-openidconnect": "^0.1.2",
    "passport-saml": "^4.0.0",
    "passport-slack": "^0.0.8",
    "passport-spotify": "^2.0.0",
    "passport-steam": "^1.0.0",
    "passport-strategy": "^1.0.0",
    "passport-twitch": "^1.0.0",
    "passport-windowsauth": "^2.1.0",
    "password-hash": "^1.2.2",
    "password-validator": "^5.3.0",
    "path": "^0.12.7",
    "path-browserify": "^1.0.1",
    "path-exists": "^5.0.0",
    "path-is-absolute": "^2.0.0",
    "path-key": "^4.0.0",
    "path-parse": "^1.0.7",
    "path-to-regexp": "^6.2.0",
    "path-type": "^5.0.0",
    "pause": "^0.1.0",
    "pem": "^1.14.0",
    "pg-copy-streams": "^6.0.0",
    "pg-cursor": "^2.9.0",
    "pg-native": "^3.0.0",
    "pg-pool": "^3.6.0",
    "pg-promise": "^11.0.0",
    "phantomjs-prebuilt": "^2.1.16",
    "pidusage": "^3.0.0",
    "pify": "^6.0.0",
    "pino-http": "^9.0.0",
    "pino-pretty": "^10.3.0",
    "pkg-dir": "^8.0.0",
    "pkg-up": "^5.0.0",
    "platform": "^1.3.6",
    "pm2": "^5.3.0",
    "pngjs": "^7.0.0",
    "point-in-polygon": "^1.1.0",
    "polka": "^1.0.0-next.22",
    "polygon-lookup": "^1.0.0",
    "polygon-selfintersect": "^1.0.0",
    "pony-cause": "^2.1.0",
    "popper.js": "^1.16.1",
    "portfinder": "^1.0.32",
    "postcss": "^8.4.0",
    "postgres": "^3.4.0",
    "postgres-array": "^3.0.0",
    "postgres-interval": "^4.0.0",
    "pouchdb": "^8.0.0",
    "prebuild-install": "^7.1.0",
    "precond": "^0.2.3",
    "pretty-bytes": "^6.1.0",
    "pretty-format": "^29.7.0",
    "pretty-ms": "^8.0.0",
    "prettyjson": "^1.2.5",
    "prettyquick": "^1.0.0",
    "preview-email": "^3.0.0",
    "prismarine-nbt": "^2.0.0",
    "prisma": "^5.6.0",
    "private-ip": "^3.0.0",
    "process": "^0.11.10",
    "process-nextick-args": "^2.0.1",
    "progress": "^2.0.3",
    "progress-stream": "^2.0.0",
    "prom-client": "^15.1.0",
    "promise": "^8.3.0",
    "promise-all-props": "^1.0.0",
    "promise-limit": "^2.7.0",
    "promise-queue": "^2.2.5",
    "promise-retry": "^2.0.1",
    "promise-timeout": "^1.3.0",
    "prompts": "^2.4.2",
    "protoo-server": "^5.1.0",
    "protobufjs": "^7.2.0",
    "proxy-addr": "^2.0.7",
    "proxy-agent": "^6.3.0",
    "proxy-from-env": "^1.1.0",
    "proxyquire": "^2.1.3",
    "ps-list": "^8.0.0",
    "ps-tree": "^1.2.0",
    "pseudomap": "^1.0.2",
    "psl": "^1.9.0",
    "pstree.remy": "^1.1.8",
    "pump": "^3.0.0",
    "pumpify": "^2.0.1",
    "punycode": "^2.3.0",
    "pure-rand": "^6.0.0",
    "q": "^1.5.1",
    "q-io": "^1.13.6",
    "qrcode-terminal": "^0.12.0",
    "qr-image": "^3.2.0",
    "qs-middleware": "^1.0.3",
    "query-string": "^8.1.0",
    "querystring": "^0.2.1",
    "querystringify": "^2.2.0",
    "quick.db": "^9.1.0",
    "quick-lru": "^7.0.0",
    "r": "^0.0.4",
    "radix64": "^1.1.2",
    "random-bytes": "^1.0.0",
    "randombytes": "^2.1.0",
    "randomstring": "^1.3.0",
    "range-parser": "^1.2.1",
    "raven": "^2.6.4",
    "raw-body": "^2.5.0",
    "rc": "^1.2.8",
    "re2": "^1.20.0",
    "react-ace": "^11.0.0",
    "react-beautiful-dnd": "^13.1.0",
    "react-chartjs-2": "^5.2.0",
    "react-color": "^2.19.3",
    "react-copy-to-clipboard": "^5.1.0",
    "react-csv": "^2.2.0",
    "react-dnd": "^16.0.0",
    "react-document-title": "^2.0.3",
    "react-dropzone": "^14.2.0",
    "react-error-boundary": "^4.0.0",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^7.48.0",
    "react-hot-toast": "^2.4.0",
    "react-icons": "^5.0.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-intersection-observer": "^9.5.0",
    "react-json-view": "^1.21.3",
    "react-lazy-load-image-component": "^1.5.1",
    "react-leaflet": "^4.2.0",
    "react-markdown": "^9.0.0",
    "react-modal": "^3.16.0",
    "react-paginate": "^8.2.0",
    "react-player": "^2.13.0",
    "react-query": "^3.39.3",
    "react-slick": "^0.29.0",
    "react-syntax-highlighter": "^15.5.0",
    "react-table": "^7.8.0",
    "react-tabs": "^6.0.0",
    "react-toastify": "^9.1.0",
    "react-tooltip": "^5.21.0",
    "react-typed": "^2.0.12",
    "react-virtualized": "^9.22.0",
    "realm": "^12.0.0",
    "reaptcha": "^3.0.0",
    "rebass": "^4.0.7",
    "redis-json": "^2.0.0",
    "redis-lock": "^1.0.0",
    "redis-search": "^1.1.0",
    "redshift": "^2.0.0",
    "redux-observable": "^3.0.0",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.2.0",
    "ref-napi": "^3.0.0",
    "reflect-metadata": "^0.2.0",
    "regenerator-runtime": "^0.14.0",
    "regexp-tree": "^0.1.27",
    "registry-auth-token": "^5.0.0",
    "registry-url": "^6.0.0",
    "release-zalgo": "^1.0.0",
    "remark": "^15.0.0",
    "remarkable": "^2.0.1",
    "remove-trailing-separator": "^1.1.0",
    "render-if": "^1.0.1",
    "repeat-element": "^1.1.4",
    "repeat-string": "^1.6.1",
    "replace-in-file": "^7.0.0",
    "request": "^2.88.2",
    "request-ip": "^3.3.0",
    "request-promise": "^4.2.6",
    "require-directory": "^2.1.1",
    "require-from-string": "^2.0.2",
    "require-js": "^1.0.0",
    "require-main-filename": "^2.0.0",
    "requireindex": "^1.2.0",
    "resolve": "^1.22.0",
    "resolve-cwd": "^3.0.0",
    "resolve-from": "^5.0.0",
    "resolve-url": "^0.2.1",
    "ret": "^0.2.2",
    "retry": "^0.13.1",
    "retry-as-promised": "^7.0.0",
    "revalidator": "^0.3.1",
    "reveal.js": "^5.0.0",
    "rev-hash": "^4.0.0",
    "rfc6902": "^5.0.0",
    "rhea": "^3.0.0",
    "rheostat": "^4.0.0",
    "rimraf": "^5.0.0",
    "riot": "^7.0.0",
    "rivets": "^0.10.0",
    "robots-parser": "^3.0.0",
    "rocksdb": "^5.0.0",
    "routington": "^2.0.0",
    "rrdtool": "^0.2.0",
    "rsa-key": "^1.0.0",
    "rsvp": "^4.8.5",
    "rtc-tools": "^1.0.0",
    "rword": "^3.2.0",
    "s3-upload-stream": "^1.0.7",
    "sade": "^1.8.0",
    "safe-buffer": "^5.2.1",
    "safe-json-stringify": "^1.2.0",
    "safe-regex": "^2.1.1",
    "sailthru-client": "^3.0.0",
    "samlify": "^4.0.0",
    "sane": "^4.1.0",
    "saslprep": "^1.0.3",
    "sax": "^1.3.0",
    "saxen": "^8.0.0",
    "say": "^0.16.0",
    "sc-auth": "^7.0.0",
    "sc-errors": "^2.0.0",
    "sc-framework-health-check": "^3.0.0",
    "sc-hot-reboot": "^3.0.0",
    "sc-params": "^1.0.0",
    "sc-request": "^2.0.0",
    "sc-ws": "^8.0.0",
    "scandirectory": "^3.0.0",
    "scandir": "^4.0.0",
    "scheduler": "^0.23.0",
    "schema-inspector": "^2.0.0",
    "schema-utils": "^4.0.0",
    "scoped-http-client": "^1.0.0",
    "scramjet": "^4.37.0",
    "scroll": "^3.0.1",
    "scrollparent": "^2.0.1",
    "scrypt": "^6.0.3",
    "scrypt-js": "^3.0.1",
    "sdsl": "^2.0.0",
    "seamless-immutable": "^7.1.4",
    "secure-json-parse": "^2.7.0",
    "secure-password": "^4.0.0",
    "selectn": "^1.1.2",
    "selenium-webdriver": "^4.15.0",
    "semaphore": "^1.1.0",
    "semver": "^7.5.0",
    "send": "^0.18.0",
    "sendgrid": "^5.2.3",
    "sentence-case": "^3.0.0",
    "sequelize": "^6.33.0",
    "sequelize-cli": "^6.6.0",
    "serialize-error": "^11.0.0",
    "serialize-javascript": "^6.0.0",
    "serve-favicon": "^2.5.0",
    "serve-index": "^1.9.1",
    "serve-static": "^1.15.0",
    "session-file-store": "^1.5.0",
    "set-cookie-parser": "^2.6.0",
    "set-immediate-shim": "^2.0.0",
    "set-value": "^4.1.0",
    "setprototypeof": "^1.2.0",
    "settle-promise": "^1.0.0",
    "sha": "^3.0.0",
    "sha.js": "^2.4.11",
    "sha1": "^1.1.1",
    "shadowsocks": "^1.0.0",
    "shallow-clone": "^3.0.1",
    "shallowequal": "^1.1.0",
    "sharedb": "^3.0.0",
    "sharedb-mongo": "^4.0.0",
    "sharedb-redis": "^3.0.0",
    "sharp2": "^0.2.0",
    "shebang-command": "^2.0.0",
    "shebang-regex": "^4.0.0",
    "shell": "^0.5.0",
    "shell-quote": "^1.8.0",
    "shelljs": "^0.8.5",
    "shimmer": "^1.2.1",
    "shortid": "^2.2.16",
    "should": "^13.2.3",
    "showdown": "^2.1.0",
    "siginfo": "^2.0.0",
    "signal-exit": "^4.0.0",
    "signale": "^1.4.0",
    "silk-sms": "^1.0.0",
    "simctl": "^2.0.0",
    "simon": "^1.1.0",
    "simple-assign": "^0.1.0",
    "simple-git": "^3.21.0",
    "simple-jsonrpc": "^1.0.0",
    "simple-lru-cache": "^0.0.2",
    "simple-oauth2": "^5.0.0",
    "simple-peer": "^9.11.0",
    "simple-statistics": "^7.8.0",
    "single-line-log": "^1.1.2",
    "sinon": "^17.0.0",
    "sip.js": "^0.21.0",
    "sitemap": "^7.1.0",
    "six": "^0.0.1",
    "size-limit": "^10.0.0",
    "sizzle": "^2.3.6",
    "skmeans": "^0.9.7",
    "slash": "^5.0.0",
    "sleep": "^6.3.0",
    "slice-ansi": "^5.0.0",
    "slide": "^1.1.6",
    "smart-buffer": "^4.2.0",
    "smtp-server": "^3.13.0",
    "snake-case": "^3.0.4",
    "snakeize": "^0.1.0",
    "snappy": "^7.2.0",
    "snekfetch": "^4.0.4",
    "snoowrap": "^2.1.0",
    "snowflake-sdk": "^1.6.0",
    "snyk": "^1.1260.0",
    "soap": "^1.0.0",
    "sockjs": "^0.3.24",
    "sodium-native": "^4.0.0",
    "solid-auth-client": "^2.5.0",
    "solidity-coverage": "^0.8.0",
    "sonic-boom": "^3.0.0",
    "sort-keys": "^5.0.0",
    "sound-play": "^1.1.0",
    "source-map": "^0.7.4",
    "spark-md5": "^3.0.2",
    "sparse-bitfield": "^3.0.3",
    "spatial-hash": "^2.0.0",
    "speakeasy": "^2.0.0",
    "speaker": "^0.5.4",
    "spectacle": "^9.1.0",
    "spectron": "^19.0.0",
    "speech-sdk": "^1.34.0",
    "speechly": "^4.0.0",
    "speedometer": "^1.1.0",
    "spellchecker": "^3.7.0",
    "split": "^1.0.1",
    "split2": "^4.2.0",
    "spotify-api": "^1.0.0",
    "spotify-uri": "^2.1.0",
    "springbokjs": "^0.1.0",
    "sql-template-strings": "^2.2.2",
    "sqlite": "^5.0.0",
    "sqlite3": "^5.1.0",
    "sqlstring": "^2.3.2",
    "squirrelly": "^9.0.0",
    "ssh2": "^1.15.0",
    "sshpk": "^1.17.0",
    "ssl-root-cas": "^1.3.1",
    "stack-trace": "^0.0.10",
    "stack-utils": "^2.0.6",
    "stact": "^0.1.0",
    "standard-error": "^1.1.0",
    "standard-http-error": "^2.0.0",
    "static-extend": "^0.1.2",
    "stats-lite": "^2.2.0",
    "statuses": "^2.0.1",
    "std-env": "^3.4.0",
    "stream-buffers": "^3.0.2",
    "stream-chain": "^2.2.5",
    "stream-combiner": "^0.2.2",
    "stream-consume": "^0.1.1",
    "stream-each": "^1.2.3",
    "stream-events": "^1.0.5",
    "stream-json": "^1.8.0",
    "stream-meter": "^1.0.4",
    "stream-promise": "^3.2.0",
    "stream-shift": "^1.0.1",
    "stream-to-array": "^2.3.0",
    "stream-to-string": "^1.2.0",
    "stream-transform": "^2.1.0",
    "strict-uri-encode": "^2.0.0",
    "string": "^3.3.3",
    "string-argv": "^0.3.2",
    "string-format": "^2.0.0",
    "string-hash": "^1.1.3",
    "string-length": "^5.0.1",
    "string-similarity": "^4.0.4",
    "string-width": "^6.1.0",
    "string.prototype.matchall": "^4.0.10",
    "stringify-entities": "^4.0.3",
    "stringify-object": "^4.0.1",
    "stringmap": "^0.2.2",
    "strip-ansi": "^7.1.0",
    "strip-bom": "^5.0.0",
    "strip-comments": "^2.0.1",
    "strip-css-comments": "^5.0.0",
    "strip-eof": "^2.0.0",
    "strip-final-newline": "^3.0.0",
    "strip-indent": "^4.0.0",
    "strip-json-comments": "^5.0.0",
    "stripe-webhook-middleware": "^3.0.0",
    "strong-error-handler": "^3.5.0",
    "stubborn-fs": "^1.2.0",
    "styled-components": "^6.1.0",
    "stylis": "^4.3.0",
    "subleveldown": "^6.0.0",
    "subsume": "^3.0.0",
    "sudo-block": "^4.0.0",
    "sumchecker": "^3.0.1",
    "supports-color": "^9.4.0",
    "supports-hyperlinks": "^3.0.0",
    "surge": "^0.23.1",
    "swagger-jsdoc": "^6.2.8",
    "swagger-parser": "^10.0.0",
    "swagger-ui-dist": "^5.9.0",
    "swagger-ui-express": "^5.0.0",
    "swagger2": "^2.0.0",
    "swarm-js": "^0.1.42",
    "symbol": "^0.3.1",
    "symbol-observable": "^4.0.0",
    "synchronous-promise": "^2.0.17",
    "syncthrough": "^2.0.0",
    "systeminformation": "^5.21.0",
    "table": "^6.8.0",
    "tabtab": "^3.0.2",
    "tail": "^2.2.6",
    "tailwindcss": "^3.3.0",
    "tapable": "^2.2.1",
    "tape": "^5.7.0",
    "tar": "^6.2.0",
    "tar-fs": "^3.0.0",
    "tar-stream": "^3.1.0",
    "tasklist": "^5.0.0",
    "tcp-port-used": "^1.0.2",
    "tdigest": "^0.1.2",
    "teachable-machine": "^1.0.0",
    "tedious": "^16.0.0",
    "teeny-request": "^9.0.0",
    "telegram-bot-api": "^2.0.0",
    "telejson": "^7.2.0",
    "temp": "^0.9.4",
    "temp-dir": "^3.0.0",
    "temp-write": "^5.0.0",
    "terminal-kit": "^3.0.0",
    "terminal-link": "^3.0.0",
    "terser": "^5.24.0",
    "test-listen": "^1.1.0",
    "testcafe": "^3.5.0",
    "text-encoding": "^0.7.0",
    "text-table": "^0.2.0",
    "textarea-caret": "^3.1.0",
    "then-request": "^6.0.0",
    "thenify": "^3.3.1",
    "throat": "^6.0.2",
    "throng": "^5.0.0",
    "through": "^2.3.8",
    "through2": "^4.0.2",
    "thunky": "^1.1.0",
    "timers-browserify": "^2.0.12",
    "timespan": "^2.3.0",
    "tiny-emitter": "^2.1.0",
    "tiny-invariant": "^1.3.1",
    "tiny-lru": "^11.2.0",
    "tiny-memcached": "^1.5.0",
    "tiny-promisify": "^1.0.0",
    "tiny-warning": "^1.0.3",
    "tinycolor2": "^1.6.0",
    "tldjs": "^2.3.1",
    "tmp": "^0.2.1",
    "to-array": "^0.1.4",
    "to-fast-properties": "^4.0.0",
    "to-identifier": "^1.0.1",
    "to-regex": "^3.0.2",
    "to-regex-range": "^5.0.1",
    "to-space-case": "^2.0.0",
    "toad-scheduler": "^3.0.0",
    "toidentifier": "^1.0.1",
    "token-stream": "^1.0.0",
    "tokgen": "^2.0.0",
    "toml": "^3.0.0",
    "topo": "^3.0.3",
    "torrent-stream": "^1.0.0",
    "totalist": "^3.0.0",
    "touch": "^3.1.0",
    "tough-cookie": "^4.1.0",
    "tr46": "^5.0.0",
    "trace-events": "^1.0.0",
    "traceur": "^0.0.111",
    "tracking": "^1.1.3",
    "traverse": "^0.6.7",
    "tree-kill": "^1.2.2",
    "tress": "^2.0.0",
    "tweetnacl": "^1.0.3",
    "tweetnacl-util": "^0.15.1",
    "twitter": "^1.7.1",
    "twit": "^2.2.11",
    "twilio": "^4.0.0",
    "type": "^2.7.0",
    "type-check": "^0.4.0",
    "type-detect": "^4.0.8",
    "type-fest": "^4.8.0",
    "type-is": "^1.6.18",
    "typed-emitter": "^2.1.0",
    "typedarray": "^0.0.6",
    "typedoc-plugin-markdown": "^3.17.0",
    "typeforce": "^1.18.0",
    "typeorm-seeding": "^2.0.0",
    "typescript-json-schema": "^0.62.0",
    "ua-parser-js": "^1.0.35",
    "uc-first": "^2.0.0",
    "uglify-js": "^3.17.0",
    "uid-safe": "^2.1.5",
    "uid2": "^1.0.0",
    "ultron": "^1.1.1",
    "umbraco": "^0.1.0",
    "unbzip2-stream": "^1.4.3",
    "unc-path-regex": "^0.1.2",
    "undici": "^6.0.0",
    "unfetch": "^5.0.0",
    "unicode-trie": "^2.0.0",
    "unified": "^11.0.0",
    "union": "^0.5.0",
    "union-value": "^2.0.0",
    "uniq": "^1.0.1",
    "uniqid": "^5.4.0",
    "unique-filename": "^3.0.0",
    "unique-string": "^3.0.0",
    "unist-util-stringify-position": "^4.0.0",
    "universal-analytics": "^0.5.3",
    "universal-cookie": "^6.1.0",
    "universalify": "^2.0.0",
    "unix-dgram": "^2.0.4",
    "unix-socket": "^1.0.0",
    "unorm": "^1.6.0",
    "unpipe": "^1.0.0",
    "unzip": "^0.1.11",
    "unzipper": "^0.10.14",
    "upath": "^2.0.1",
    "update-notifier": "^7.0.0",
    "uri-js": "^4.4.1",
    "urijs": "^1.19.11",
    "url": "^0.11.3",
    "url-join": "^5.0.0",
    "url-parse": "^1.5.10",
    "url-search-params": "^1.1.0",
    "url-to-options": "^2.0.0",
    "urlencode": "^2.0.0",
    "urlgrey": "^2.0.0",
    "use-deep-compare-effect": "^1.8.1",
    "use-http": "^1.0.0",
    "use-immer": "^0.9.0",
    "use-local-storage-state": "^19.0.0",
    "use-media": "^1.4.0",
    "use-query-params": "^2.2.0",
    "use-resize-observer": "^10.0.0",
    "use-state-history": "^1.0.0",
    "use-undo": "^1.0.0",
    "user-agent": "^1.0.4",
    "username": "^6.0.0",
    "uslug": "^1.0.4",
    "utf-8-validate": "^6.0.0",
    "util": "^0.12.5",
    "util-deprecate": "^1.0.2",
    "util-extend": "^1.0.3",
    "util-inspect": "^0.1.8",
    "util-promisify": "^2.1.0",
    "util.promisify": "^1.1.1",
    "utile": "^0.3.0",
    "utility-types": "^3.10.0",
    "uuid-parse": "^1.1.0",
    "uuid4": "^2.0.0",
    "v8-compile-cache": "^2.4.0",
    "v8-util": "^1.0.0",
    "valid-url": "^1.0.9",
    "validate-npm-package-name": "^5.0.0",
    "validate.js": "^0.13.1",
    "validatorjs": "^3.22.0",
    "value-equal": "^2.0.0",
    "vary": "^1.1.2",
    "velocityjs": "^2.0.6",
    "verror": "^1.10.1",
    "vhost": "^3.0.2",
    "video.js": "^8.5.0",
    "viewerjs": "^1.11.0",
    "vinyl": "^3.0.0",
    "vinyl-fs": "^4.0.0",
    "virtual-dom": "^2.1.1",
    "vis-network": "^9.1.0",
    "vite": "^5.0.0",
    "vm2": "^3.9.0",
    "vue": "^3.3.0",
    "vue-router": "^4.2.0",
    "vuex": "^4.1.0",
    "wait-on": "^7.0.0",
    "wake_on_lan": "^1.0.0",
    "wake-lock": "^1.0.0",
    "walk": "^2.3.15",
    "wav-decoder": "^1.3.0",
    "wcwidth": "^1.0.1",
    "web-audio-engine": "^0.14.0",
    "web-audio-test-api": "^0.5.2",
    "web-namespaces": "^2.0.0",
    "web-push-helper": "^2.0.0",
    "web-worker": "^1.3.0",
    "web3-core": "^4.3.0",
    "web3-eth-contract": "^4.3.0",
    "web3-providers-http": "^4.1.0",
    "web3-utils": "^4.1.0",
    "webcrypto-core": "^1.7.0",
    "webcrypto-shim": "^0.1.6",
    "webidl-conversions": "^7.0.0",
    "webpack-dev-middleware": "^7.0.0",
    "webpack-hot-middleware": "^2.26.0",
    "webpack-merge": "^5.10.0",
    "webpack-node-externals": "^3.0.0",
    "webpackbar": "^5.0.0",
    "webrtc-adapter": "^8.2.0",
    "websocket": "^1.0.34",
    "websocket-as-promised": "^2.0.0",
    "websocket-driver": "^0.7.4",
    "websocket-extensions": "^0.1.4",
    "websocket-stream": "^5.5.2",
    "whatwg-fetch": "^3.6.0",
    "whatwg-mimetype": "^4.0.0",
    "whatwg-url": "^13.0.0",
    "when": "^3.7.8",
    "which": "^4.0.0",
    "whisper-node": "^1.0.0",
    "wifi-name": "^5.0.0",
    "win-ca": "^3.5.0",
    "winreg": "^1.2.4",
    "winston-elasticsearch": "^0.17.0",
    "winston-loggly-bulk": "^3.4.0",
    "winston-mongodb": "^6.0.0",
    "winston-syslog": "^2.6.0",
    "wiredep": "^4.0.0",
    "word": "^0.3.0",
    "word-wrap": "^1.2.5",
    "wordcloud": "^1.0.0",
    "wordextractor": "^1.0.0",
    "wordwrap": "^1.0.0",
    "workbox-webpack-plugin": "^7.0.0",
    "worker-farm": "^1.7.0",
    "workerpool": "^6.5.0",
    "wrap-ansi": "^9.0.0",
    "wrappy": "^1.0.2",
    "write": "^2.0.0",
    "write-file-atomic": "^5.0.0",
    "write-json-file": "^6.0.0",
    "ws": "^8.16.0",
    "wtfnode": "^0.9.1",
    "x-ray": "^2.3.4",
    "x509": "^1.0.0",
    "xbee-api": "^0.6.0",
    "xlsx-style": "^0.8.13",
    "xml-crypto": "^3.0.0",
    "xml-encryption": "^2.0.0",
    "xml-formatter": "^3.4.0",
    "xml-parser": "^1.2.1",
    "xml2js": "^0.6.2",
    "xml2json": "^0.12.0",
    "xmlbuilder": "^15.1.1",
    "xmldom": "^0.6.0",
    "xmlhttprequest": "^1.8.0",
    "xmlhttprequest-ssl": "^1.6.3",
    "xpath": "^0.0.33",
    "xregexp": "^5.1.0",
    "xss-filters": "^1.2.7",
    "xtend": "^4.0.2",
    "y18n": "^6.0.0",
    "yallist": "^4.0.0",
    "yaml": "^2.3.0",
    "yaml-ast-parser": "^0.0.43",
    "yaml-front-matter": "^4.1.0",
    "yamljs": "^0.3.0",
    "yargs": "^17.7.0",
    "yargs-parser": "^21.1.0",
    "yauzl": "^2.10.0",
    "yazl": "^2.5.1",
    "youtube-api": "^3.0.0",
    "youtube-dl": "^3.0.0",
    "youtube-dl-exec": "^2.0.0",
    "youtube-node": "^3.0.0",
    "youtube-search": "^1.2.0",
    "youtube-sr": "^4.0.0",
    "ytdl-core-react": "^1.0.0",
    "z-schema": "^6.0.0",
    "zalgo-promise": "^1.0.0",
    "zangodb": "^0.12.0",
    "zepto": "^1.2.0",
    "zeromq": "^6.0.0",
    "zone.js": "^0.14.0",
    "zookeeper": "^2.0.0",
    "zopfli": "^2.1.0",
    "zpipe": "^1.0.0",
    "zstd": "^0.1.0",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@babel/core": "^7.23.0",
    "@babel/preset-env": "^7.23.0",
    "@babel/preset-react": "^7.23.0",
    "@babel/preset-typescript": "^7.23.0",
    "@commitlint/cli": "^18.0.0",
    "@commitlint/config-conventional": "^18.0.0",
    "@graphql-codegen/cli": "^5.0.0",
    "@graphql-codegen/typescript": "^4.0.0",
    "@graphql-codegen/typescript-resolvers": "^4.0.0",
    "@nestjs/cli": "^10.0.0",
    "@nestjs/schematics": "^10.0.0",
    "@nestjs/testing": "^10.0.0",
    "@playwright/test": "^1.40.0",
    "@storybook/addon-actions": "^7.5.0",
    "@storybook/addon-essentials": "^7.5.0",
    "@storybook/addon-links": "^7.5.0",
    "@storybook/react": "^7.5.0",
    "@swc/cli": "^0.1.0",
    "@swc/core": "^1.3.100",
    "@swc/jest": "^0.2.0",
    "@testing-library/jest-dom": "^6.1.0",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.5.0",
    "@types/amqplib": "^0.10.0",
    "@types/bull": "^4.0.0",
    "@types/chart.js": "^2.9.0",
    "@types/cheerio": "^0.22.0",
    "@types/compression": "^1.7.0",
    "@types/cookie-parser": "^1.4.0",
    "@types/cron": "^2.0.0",
    "@types/d3": "^7.4.0",
    "@types/express-rate-limit": "^6.0.0",
    "@types/express-session": "^1.17.0",
    "@types/fluent-ffmpeg": "^2.1.0",
    "@types/graphql": "^14.5.0",
    "@types/handlebars": "^4.1.0",
    "@types/helmet": "^4.0.0",
    "@types/jest": "^29.5.0",
    "@types/jsonwebtoken": "^9.0.0",
    "@types/morgan": "^1.9.0",
    "@types/multer": "^1.4.0",
    "@types/node": "^20.0.0",
    "@types/node-cron": "^3.0.0",
    "@types/nodemailer": "^6.4.0",
    "@types/oauth": "^0.9.0",
    "@types/passport": "^1.0.0",
    "@types/passport-facebook": "^3.0.0",
    "@types/passport-google-oauth20": "^2.0.0",
    "@types/passport-jwt": "^4.0.0",
    "@types/passport-local": "^1.0.0",
    "@types/puppeteer": "^7.0.0",
    "@types/redis": "^4.0.0",
    "@types/socket.io": "^3.0.0",
    "@types/supertest": "^6.0.0",
    "@types/swagger-ui-express": "^4.1.0",
    "@types/uuid": "^9.0.0",
    "@types/web-push": "^3.3.0",
    "@types/ws": "^8.5.0",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vue/test-utils": "^2.4.0",
    "autoprefixer": "^10.4.0",
    "babel-jest": "^29.7.0",
    "babel-loader": "^9.1.0",
    "chai": "^4.3.0",
    "cypress": "^13.5.0",
    "eslint-config-next": "^14.0.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-cypress": "^2.15.0",
    "eslint-plugin-jest": "^27.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react": "^7.33.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-security": "^1.7.0",
    "eslint-plugin-unused-imports": "^3.0.0",
    "husky": "^8.0.0",
    "jest-environment-node": "^29.7.0",
    "jest-extended": "^4.0.0",
    "jest-html-reporter": "^3.10.0",
    "jest-junit": "^16.0.0",
    "jest-mock-extended": "^3.0.0",
    "jest-sonar-reporter": "^2.0.0",
    "lint-staged": "^15.0.0",
    "mocha": "^10.2.0",
    "nodemon": "^3.0.0",
    "nyc": "^15.1.0",
    "postcss-loader": "^7.3.0",
    "prettier": "^3.0.0",
    "prettier-plugin-tailwindcss": "^0.5.0",
    "react-test-renderer": "^18.2.0",
    "redux-devtools": "^3.7.0",
    "redux-mock-store": "^1.5.4",
    "sass-loader": "^13.3.0",
    "style-loader": "^3.3.0",
    "supertest": "^6.3.0",
    "tailwindcss": "^3.3.0",
    "ts-jest": "^29.1.0",
    "ts-loader": "^9.5.0",
    "ts-node-dev": "^2.0.0",
    "tsconfig-paths": "^4.2.0",
    "typedoc": "^0.25.0",
    "typescript-styled-plugin": "^0.18.0",
    "webpack-dev-server": "^4.15.0"
  },
  "engines": {
    "node": ">=20.0.0",
    "npm": ">=10.0.0",
    "yarn": ">=1.22.0",
    "pnpm": ">=8.0.0"
  },
  "os": [
    "linux",
    "darwin",
    "win32",
    "android",
    "ios"
  ],
  "cpu": [
    "x64",
    "arm64",
    "ia32",
    "arm"
  ],
  "private": true,
  "workspaces": [
    "packages/backend",
    "packages/frontend",
    "packages/mobile",
    "packages/desktop",
    "packages/shared",
    "packages/ai-models",
    "packages/blockchain",
    "packages/iot",
    "packages/robotics",
    "packages/ar-vr",
    "packages/gaming",
    "packages/quantum",
    "packages/bioinformatics",
    "packages/space-tech"
  ],
  "lint-staged": {
    "*.{ts,tsx,js,jsx}": [
      "eslint --fix",
      "prettier --write"
    ],
    "*.{json,md,yml,yaml,css,scss}": [
      "prettier --write"
    ],
    "*.{graphql,gql}": [
      "prettier --write"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
      "pre-push": "npm run test:ultimate && npm run type-check:ultimate",
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "post-merge": "npm install",
      "post-rewrite": "npm install"
    }
  },
  "config": {
    "mongodb": "mongodb://localhost:27017/zass-ultimate",
    "postgres": "postgresql://localhost:5432/zass-ultimate",
    "redis": "redis://localhost:6379",
    "elasticsearch": "http://localhost:9200",
    "port": 3000,
    "websocket_port": 3001,
    "grpc_port": 50051,
    "graphql_port": 4000,
    "metrics_port": 9090
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "not ie > 0",
      "not edge < 79",
      "not safari < 12"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "last 1 edge version"
    ]
  },
  "overrides": {
    "node-fetch": "^3.3.2",
    "qs": "^6.11.2",
    "semver": "^7.5.4"
  },
  "resolutions": {
    "**/lodash": "^4.17.21",
    "**/underscore": "^1.13.6"
  }
}
